# Generated by Django 3.0.2 on 2020-01-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('ownerUsername', models.TextField()),
                ('borrowerUsername', models.TextField(blank=True)),
                ('datepublished', models.DateField(blank=True)),
                ('isbnthirteen', models.TextField()),
                ('publisher', models.TextField()),
                ('datelastmodified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
